### PR TITLE
Add support for laravel 11, and add then use the latest php 8.3 version

### PR DESCRIPTION
**Pull request by lloricode**
additional changes of https://github.com/timacdonald/json-api/pull/49

### CODE REVIEW

**Comment by lloricode** [comment]
⚗️ Using this package? If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:
```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/lloricode/json-api.git"
        }
    ]
}
```
Then update your dependency constraint to reference this branch:
```json
{
    "require": {
        "timacdonald/json-api": "dev-l11-compatibility",
    }
}
```
Finally, run: `composer update`

**Review by jbrooksuk — APPROVED** [review]
@timacdonald 🙏

**Comment by lloricode** [comment]
close as continue at https://github.com/timacdonald/json-api/pull/49

**Comment by timacdonald** [comment]
I had to make a few extra tweaks and didn't see this one. Appreciate you sending it through.

**Pull request closed without merging**
